### ISSUE TITLE
Class not found IDisposable  

### ISSUE THREAD

**Issue by MarwenSami** [psycopaths/jconstraints-z3#2]
Hello,
When trying to build jconstraints-z3, using the latestZ3 version I get an error: cannot find symbol: com.microsoft.z3.IDisposable.
I checked and I found out that this class no longer exists in Z3 src so I downloaded Z3 4.4.1 and the issue is solved however I get a new error: java.lang.UnsupportedClassVersionError: com/microsoft/z3/Z3Exception : Unsupported major.minor version 52.0.

Update: it works with Z3 version 4.4.0

Update2: 
Now I get a new error: JPF configuration error: error instantiating class gov.nasa.jpf.jdart.JDart for entry "shell":

> exception in gov.nasa.jpf.jdart.JDart(gov.nasa.jpf.Config):
> 
> > java.lang.NoClassDefFoundError: com/microsoft/z3/Z3Exception

**Comment by ksluckow** [comment]
Hi,
Thanks for reporting this! Unfortunately, the z3 api keeps changing (and thus the Java bindings) --- it is a moving target. I wonder why `IDisposable` has been removed...
I'll try looking into this, but It's likely non-trivial, so for now, please stick with the Z3 version that works with jConstraints. I'll keep you posted.

The `Unsupported major.minor version 52.0.` you get is because you compiled z3(?) with Java 1.8 compliance level, and you are using a JRE with a lower compliance level (possibly 1.7).

**Comment by ksluckow** [comment]
On my machine, jconstraints-z3 works with Z3 v4.4.1.
I have updated the README and POM with new installation instructions etc. for that version of Z3.

**Comment by MarwenSami** [comment]
Thank you for the reply, I did as you mentionned, I recompiled Z3 v4.4.1 with Java 1.8 and I run JDart with 1.8 JRE but I'm getting this error: 
java.lang.NoClassDefFoundError: com/microsoft/z3/Z3Exception
    at gov.nasa.jpf.Config.getInstance(Config.java:2015)
    at gov.nasa.jpf.Config.getInstance(Config.java:1889)
    at gov.nasa.jpf.Config.getInstance(Config.java:1880)
    at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:106)

I'm running the using.jpf file in JDart on a windows 8.1 machine x64.

**Comment by MarwenSami** [comment]
Never mind I fixed the problem by adding com.microsoft.z3.jar and jconstraints-0.9.1-SNAPSHOT.jar to .jconstraints\extensions folder. (it wasn't mentionned in the README that those 2 jars must be in there with jconstraints-z3-[version].jar though)

**Comment by ksluckow** [comment]
Sorry, I want to make sure that the documentation is correct, so I'm reopening.
In the [Building and Installing jConstraints-z3](https://github.com/psycopaths/jconstraints-z3#building-and-installing-jconstraints-z3) section it does say that you have to copy the Z3 java bindings (`com.microsoft.z3.jar`) along with the jConstraints-z3.jar you just built to `~/.jconstraints/extensions`.
If something is unclear, I'd like to fix it.

**Comment by MarwenSami** [comment]
my bad, sorry
